### ISSUE TITLE
CRUD LMS - Backend

### ISSUE THREAD

**Issue by infinitizon** [InvestNaija/INv2#58]
### Summary / Description
A LMS is any of the various types like Article, Video, Podcast, Course, Quiz or any other that may be defined in the future

### Acceptance Criteria
- Only a __SUPER_ADMIN__ or __PROVIDER__ can Create/Edit LMS
- Every create/change to LMS should triggers a version update.
- If LMS is a parent (i.e. has no pId), then emit a lms:created event

### Requirements / Specifications
p_id            // Optional: Id of parent an LMS belongs
type,           // Required: Every LMS must have a type
title,           // Required
summary,  // Required
content,     // Optional
version,      // Required

### Technical Notes

Every LMS has a type as stated below:

         {code: 101, name: 'art', label: 'Articles'}, 
         {code: 105, name: 'pod', label: 'Podcast'}, 
         {code: 110, name: 'eps', label: 'Episode'}, 
         {code: 115, name: 'vid', label: 'Video',},
         {code: 120, name: 'qz', label: 'Quiz',},
         {code: 125, name: 'rsh', label: 'Research',},
         {code: 130, name: 'ch', label: 'Chapter',},
         {code: 135, name: 'crs', label: 'Course',},

### Definition of Done
- [ ] Code Implemented
- [ ] Code Reviewed
- [ ] Tests written and passing
- [ ] Documentation updated

**Comment by jemikalajah123** [comment]
done
